server { #HTTPS
	listen 443 ssl;
	server_name dbozic.42.fr;

	ssl_certificate certifications/nginx.crt
	ssl_certificate_key certifications/nginx.key

	ssl_protocols TLSv1.2 TLSv1.3;

	ssl_ciphers HIGH:!aNULL:!MD5;

	location ~ \.php$ {
		include fastcgi_params;
		include snippets/fastcgi-php.conf
		fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name
		#TODO check the include snippets line
		#TODO check if SCRIPT_FILENAME is not redundant
	}
}

server { #redirect HTTP to HTTPS
	listen 80;
	server_name dbozic.42.fr;

	return 301 https://$
}